<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_FaultMonitor" Id="{6cc8fde6-1295-4af5-bc51-9463c95b90a2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FaultMonitor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>