<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_FlowCalcs" Id="{1756219a-0231-4cbf-99e3-e5ecc1f6178b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FlowCalcs
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>