<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_InputScaling" Id="{107f2dd2-09fa-48c0-b7c9-e9ac87e64317}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_InputScaling

VAR_OUTPUT
    stProcessValues : ST_ProcessValues;   // this FB is the only writer
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>