<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_WaterFill" Id="{a0c26368-373e-4fd3-95ee-778e79d1422c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WaterFill
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>